In [1]:
import numpy as np

In [4]:
%timeit [i+1 for i in range(10000)] # tells the time of a procedure

970 µs ± 31.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit np.arange(10000)+1

19.1 µs ± 192 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
# Creating

a = np.array([1,2,3,4,5]) # creates an array
print(a)

[1 2 3 4 5]


In [7]:
type(a)

numpy.ndarray

In [10]:
b = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [11]:
b

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [12]:
li = [1,2,3,4,5]
np.array(li)

array([1, 2, 3, 4, 5])

In [14]:
type(np.array(li))

numpy.ndarray

In [15]:
c = np.arange(100)

In [16]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
g = np.loadtxt('New Text Document.txt', delimiter= ',')
print(g)

[1. 2. 3. 4. 5.]


In [23]:
d = np.empty((3,3)) # returns an array of given shape
print(d)

[[ 1.     2.125  3.25 ]
 [ 4.375  5.5    6.625]
 [ 7.75   8.875 10.   ]]


In [25]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
g[[0,3]]  # indexing

array([1., 4.])